# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('monthly_price', models.FloatField(verbose_name='preço mensal')),
                ('users', models.IntegerField(verbose_name='número de usuários')),
                ('automatic_register', models.BooleanField(default=False, verbose_name='marcação automática')),
                ('dynamic_reminders', models.BooleanField(default=False, verbose_name='lembretes automáticos')),
                ('support_all_time', models.BooleanField(default=False, verbose_name='suporte 24/7')),
                ('is_popular', models.BooleanField(default=False, verbose_name='popular')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
            ],
        ),
    ]
