# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'plano', 'verbose_name_plural': 'planos'},
        ),
        migrations.AddField(
            model_name='plan',
            name='headline',
            field=models.CharField(default='', max_length=255, verbose_name='descrição'),
            preserve_default=False,
        ),
    ]
