# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20160530_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='gratuito'),
        ),
    ]
