# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_plan_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='unlimited_users',
            field=models.BooleanField(default=False, verbose_name='usuários ilimitados'),
        ),
    ]
