# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_plan_unlimited_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='users',
            field=models.IntegerField(default=0, verbose_name='número de usuários'),
        ),
    ]
