# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 14:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='admission_date',
            field=models.DateField(default=datetime.datetime(2016, 6, 19, 14, 26, 13, 648141, tzinfo=utc), verbose_name='data de admissão'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='pis',
            field=models.CharField(default='', max_length=255, verbose_name='PIS'),
            preserve_default=False,
        ),
    ]
